import { ArrowLeft, Clock, User, Calendar, Fingerprint, BarChart3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Link } from "react-router-dom";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import RelatedPosts from "@/components/RelatedPosts";
import TableOfContents from "@/components/TableOfContents";
import WatermarkHeroDiagram from "@/components/WatermarkHeroDiagram";

const ClaudeWatermarkPost = () => {
  const labData = [
    { lab: "Google (Gemini)", status: "✓ Shipped", detail: "SynthID-Text is live in Gemini and open-sourced. Also covers images, audio, and video." },
    { lab: "Anthropic (Claude)", status: "✓ Shipped (new)", detail: "Imperceptible text watermark since Aug 2, 2026, across API, Claude, Claude Code, Cowork, Tag — worldwide. Files get C2PA metadata." },
    { lab: "OpenAI (ChatGPT)", status: "~ Built, unreleased", detail: "A ~99.9%-accurate text watermarker exists internally but is withheld over bypass and fairness concerns. DALL·E images carry C2PA metadata." },
    { lab: "Meta (Llama)", status: "✗ No text mark", detail: "Ships AudioSeal for audio; text watermarking (TextSeal) is research, not wired into Llama outputs." },
  ];

  const removeData = [
    { action: "Copy and paste as-is", effect: "Mark survives — it's in the word choices, not metadata", verdict: "Still detectable" },
    { action: "Fix a few typos / light edits", effect: "Mark usually persists", verdict: "Likely detectable" },
    { action: "Paraphrase / reword heavily", effect: "Statistical signal degrades fast", verdict: "Often undetectable" },
    { action: "Translate to another language", effect: "Token distribution is rewritten", verdict: "Undetectable" },
    { action: "Mix AI + human text", effect: "Signal diluted below the test threshold", verdict: "Often undetectable" },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Navigation />

      <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-20">
        <div className="flex flex-col lg:flex-row gap-4 lg:gap-8">
          <TableOfContents />

          {/* Main Content */}
          <div className="flex-1 w-full max-w-none lg:max-w-4xl">
            {/* Back Button */}
            <Link to="/#blogs">
              <Button variant="ghost" className="mb-6 sm:mb-8 group">
                <ArrowLeft className="mr-2 h-4 w-4 group-hover:-translate-x-1 transition-transform" />
                <span className="text-sm sm:text-base">Back to Insights</span>
              </Button>
            </Link>

            {/* Article Header */}
            <header className="mb-8 sm:mb-12">
              <div className="flex items-center space-x-2 mb-4">
                <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-sky-600 to-indigo-800 rounded-full px-3 py-1">
                  <Fingerprint className="h-4 w-4 text-primary-foreground" />
                  <span className="text-sm font-medium text-primary-foreground">AI Security</span>
                </div>
              </div>

              <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold mb-4 sm:mb-6 leading-tight">
                Does Claude Watermark Its Text? AI Text Watermarking (Claude, ChatGPT & SynthID), Explained
              </h1>

              <p className="text-base sm:text-lg lg:text-xl text-muted-foreground mb-6 sm:mb-8 leading-relaxed">
                Short answer: <strong>yes — as of August 2, 2026, Anthropic weaves an imperceptible watermark into text
                generated by newer Claude models</strong>, worldwide, to meet the EU AI Act's transparency code. Google's
                Gemini already does this with SynthID; OpenAI built a watermarker for ChatGPT but hasn't shipped it. Here's
                what a text watermark actually is, how it survives copy-paste but not paraphrasing, and why it is <em>not</em>
                {" "}the thing Turnitin uses to catch you.
              </p>

              {/* Author Info */}
              <Card className="p-4 sm:p-6 bg-gradient-card border-border">
                <div className="flex flex-col sm:flex-row items-start sm:items-center space-y-4 sm:space-y-0 sm:space-x-4">
                  <div className="w-12 h-12 rounded-full bg-gradient-to-r from-sky-600 to-indigo-800 flex items-center justify-center flex-shrink-0">
                    <User className="h-6 w-6 text-white" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <Link to="/authors" className="hover:text-primary transition-colors">
                      <div className="font-semibold text-base sm:text-lg hover:underline">Gurram Poorna Prudhvi</div>
                    </Link>
                    <p className="text-muted-foreground text-sm sm:text-base">Lead AI Engineer</p>
                  </div>
                  <div className="text-xs sm:text-sm text-muted-foreground space-y-1 flex-shrink-0">
                    <div className="flex items-center">
                      <BarChart3 className="h-4 w-4 mr-1" />
                      Intermediate
                    </div>
                    <div className="flex items-center">
                      <Calendar className="h-4 w-4 mr-1" />
                      Aug 14, 2026
                    </div>
                    <div className="flex items-center">
                      <Clock className="h-4 w-4 mr-1" />
                      10 min read
                    </div>
                  </div>
                </div>
              </Card>
            </header>

            {/* Hero Diagram */}
            <WatermarkHeroDiagram />

            {/* Article Content */}
            <article className="prose prose-sm sm:prose-base lg:prose-lg max-w-none">
              <section className="mb-6 sm:mb-8">
                <h2 id="tldr" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">1. The Short Answer</h2>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  On <strong>August 2, 2026</strong> — the day the EU AI Act's transparency code took effect — Anthropic began
                  embedding a machine-readable, imperceptible watermark into text generated by Claude models launched on or
                  after that date, and committed to backfilling older models during a transition period. In Anthropic's own
                  words, it <strong>"weaves an imperceptible watermark directly into the text itself. You won't see it, and it
                  doesn't change the meaning."</strong> The marking applies across the Claude Platform (API), Claude, Claude
                  Code, Claude Cowork, and Claude Tag — and, notably, <strong>worldwide</strong>, not just in the EU.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  So Claude joins Google, whose Gemini has watermarked text with SynthID since 2024. OpenAI is the outlier: it
                  built a text watermarker reported at ~99.9% accuracy but has kept it on the shelf. The rest of this piece is
                  the engineer's version — what the mark is, how it works, and its hard limits. The single most important limit
                  up front: <strong>a watermark can prove text is AI-generated when the signal is present, but its absence
                  never proves text is human.</strong>
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="what-is-it" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">2. What "Text Watermarking" Actually Means</h2>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  There are three different things people lump under "AI watermark," and they behave nothing alike:
                </p>
                <ul className="space-y-2 text-sm sm:text-base text-muted-foreground mb-4 list-disc pl-5">
                  <li><strong>A statistical text watermark</strong> — a hidden bias in <em>which words the model chooses</em>. It
                    lives in the text itself, so it survives copy-paste and reformatting. This is what Claude and SynthID use.</li>
                  <li><strong>A visible label</strong> — a "Generated by AI" disclosure or UI badge. Trivially removed; only as
                    good as the honesty of whoever pastes the text.</li>
                  <li><strong>File provenance metadata (C2PA)</strong> — a cryptographically signed manifest attached to a
                    <em> file</em> (image, PDF). Robust and verifiable, but stripped the moment you copy the content out of the
                    file. Claude attaches C2PA to supported files like <code>.svg</code>, <code>.png</code>, and <code>.jpg</code>.</li>
                </ul>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  The interesting one — and the source of all the confusion — is the statistical text watermark, because it's
                  invisible, it's not metadata you can strip, and yet it's surprisingly easy to destroy by accident. To see why,
                  you have to look at how a model actually emits a token.
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="how-it-works" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">3. How It Works Under the Hood</h2>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  At every step, an LLM produces a probability distribution over its whole vocabulary and samples the next token
                  from it. Usually many tokens are "good enough" — dozens of near-equivalent ways to continue a sentence. A
                  watermark hides a signal in that freedom of choice.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  The seminal method, <strong>Kirchenbauer et al.'s "A Watermark for Large Language Models"</strong> (2023), uses
                  a secret key to split the vocabulary at each step into a pseudo-random <strong>"green list"</strong> and
                  "red list," then softly boosts the green tokens' probabilities. Over a paragraph, watermarked text ends up with
                  statistically <em>too many</em> green tokens to be chance. A detector that knows the key recounts them and runs a
                  significance test — flagging AI generation with a p-value, no access to the model needed. Google DeepMind's
                  <strong> SynthID-Text</strong> productionized a more refined version called <strong>tournament sampling</strong>,
                  published in <em>Nature</em> in October 2024 and deployed across Gemini; the code is open-source.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  The elegance is that reading stays normal — the text means the same thing and reads the same way — while the
                  <em> distribution</em> of choices carries a fingerprint. The fragility is baked into the same fact: rewrite the
                  choices, and you rewrite the fingerprint out of existence.
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="who-watermarks" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">4. Who Watermarks Text — and Who Doesn't</h2>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  The landscape as of August 2026. Text watermarking specifically — not image/audio, which several labs ship
                  more widely:
                </p>
                <div className="overflow-x-auto mb-4 sm:mb-6 -mx-4 sm:mx-0">
                  <div className="min-w-full inline-block align-middle">
                    <div className="overflow-hidden border rounded-lg mx-4 sm:mx-0">
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead className="text-xs sm:text-sm px-2 sm:px-4">Lab (model)</TableHead>
                            <TableHead className="text-xs sm:text-sm px-2 sm:px-4">Text watermark</TableHead>
                            <TableHead className="text-xs sm:text-sm px-2 sm:px-4">Details</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {labData.map((row, index) => (
                            <TableRow key={index}>
                              <TableCell className="font-medium text-xs sm:text-sm px-2 sm:px-4">{row.lab}</TableCell>
                              <TableCell className="text-xs sm:text-sm px-2 sm:px-4">{row.status}</TableCell>
                              <TableCell className="text-xs sm:text-sm px-2 sm:px-4">{row.detail}</TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </div>
                  </div>
                </div>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  OpenAI's reasoning for holding back is worth knowing, because it's the whole policy debate in miniature: internal
                  surveys reportedly found watermarking could stigmatize AI use for non-native English speakers, and that a large
                  share of users would simply switch tools. Detection that's easy to evade but hard on honest users is a bad trade —
                  which is exactly the tension the EU AI Act is now forcing labs to resolve in public.
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="claude-detail" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">5. What Claude's Watermark Does (and Doesn't) Cover</h2>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  Two mechanisms, two jobs. For <strong>text</strong>, Claude embeds the imperceptible statistical watermark that
                  travels with copy-paste. For <strong>files</strong> it generates (like <code>.svg</code>/<code>.png</code>/<code>.jpg</code>),
                  it attaches <strong>signed C2PA provenance metadata</strong> — the same open standard OpenAI uses on DALL·E images.
                  Coverage spans the API and every Claude surface, "wherever Claude is offered, worldwide," including when Claude runs
                  via AWS, Google Cloud, or Microsoft Foundry.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  For engineers, the practical read: <strong>output from Claude Code and the API is in scope.</strong> If you ship
                  Claude-generated text or assets into a product, that content may now carry a detectable mark. Anthropic says the
                  watermark "will travel with the text when it's copied and pasted elsewhere, and may persist through some editing,"
                  while conceding it can be lost if content is "heavily edited, paraphrased, translated, or mixed into other writing."
                  A public detection tool isn't live yet — Anthropic says it "will share details on detection mechanisms in
                  forthcoming technical documentation." This is the same execution-and-provenance surface we flagged when
                  {" "}<Link to="/blog/openai-models-hacked-hugging-face" className="text-primary hover:underline">OpenAI's models escaped a sandbox and attacked Hugging Face</Link>:
                  knowing exactly what your agent emits, and how it's tracked, is now part of the job.
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="detect-remove" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">6. Can You Detect or Remove It?</h2>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  Detecting a watermark requires the <strong>matching detector and key</strong> from the lab that made it — you
                  can't eyeball it, and a generic "AI detector" isn't reading it (more on that below). Removing it, on the other
                  hand, is often accidental. Here's the honest robustness table:
                </p>
                <div className="overflow-x-auto mb-4 sm:mb-6 -mx-4 sm:mx-0">
                  <div className="min-w-full inline-block align-middle">
                    <div className="overflow-hidden border rounded-lg mx-4 sm:mx-0">
                      <Table>
                        <TableHeader>
                          <TableRow>
                            <TableHead className="text-xs sm:text-sm px-2 sm:px-4">What you do to the text</TableHead>
                            <TableHead className="text-xs sm:text-sm px-2 sm:px-4">Effect on the signal</TableHead>
                            <TableHead className="text-xs sm:text-sm px-2 sm:px-4">Result</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {removeData.map((row, index) => (
                            <TableRow key={index}>
                              <TableCell className="font-medium text-xs sm:text-sm px-2 sm:px-4">{row.action}</TableCell>
                              <TableCell className="text-xs sm:text-sm px-2 sm:px-4">{row.effect}</TableCell>
                              <TableCell className="text-xs sm:text-sm px-2 sm:px-4">{row.verdict}</TableCell>
                            </TableRow>
                          ))}
                        </TableBody>
                      </Table>
                    </div>
                  </div>
                </div>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  This isn't a vendor weakness — it's a proven property of the method. Sadasivan et al. (2023), "Can AI-Generated
                  Text Be Reliably Detected?", showed a recursive-paraphrase attack driving watermark detection from ~99.8% down to
                  under 10% with minimal quality loss. That's why the framing matters: watermarks are good for <strong>provenance at
                  scale</strong> (a platform checking its own output) and useless as an <strong>anti-cheating dragnet</strong>
                  (anyone motivated can strip them).
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="turnitin-myth" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">7. The Turnitin Myth</h2>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  The most common misconception: that Turnitin or GPTZero "read the AI watermark." <strong>They don't.</strong>
                  Those tools do not have Anthropic's, Google's, or OpenAI's secret keys, so they can't check a SynthID or Claude
                  watermark at all. Instead they run their <em>own</em> classifiers over surface statistics — perplexity, burstiness,
                  phrasing patterns — and output a probability guess. That's a fundamentally different, and much noisier, signal:
                  it produces false positives on human writing and is defeated by the same paraphrasing that defeats real watermarks.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  So there are effectively two parallel worlds: <strong>lab watermarks</strong> (accurate but only checkable by the
                  lab, and easy to strip) and <strong>third-party detectors</strong> (checkable by anyone but statistically
                  unreliable). Neither is the confident "AI or not" oracle people imagine.
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="why-now" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">8. Why This Is Happening Now: The EU AI Act</h2>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  Claude's watermark didn't appear because it suddenly became useful — it appeared because of <strong>Article 50(2)
                  of the EU AI Act</strong>, whose transparency code took effect August 2, 2026. It requires providers of generative
                  systems to mark AI-generated or edited content in a machine-readable way that other systems can identify. Anthropic
                  chose to implement it <em>globally</em> rather than geofence the EU — simpler to build one pipeline than two, and it
                  aligns with a broader industry move toward content provenance (C2PA / Content Credentials) that Adobe, Microsoft,
                  Google, and OpenAI have all signed onto for media.
                </p>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  Expect the same from the other labs on the same clock. The regulation doesn't require the watermark to be
                  unbreakable — only present and machine-readable — which tells you how policymakers are thinking about it: a
                  provenance signal for the honest majority, not a forensic weapon against the determined few.
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="faq" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">9. Frequently Asked Questions</h2>

                <h3 id="faq-claude" className="text-lg sm:text-xl font-semibold mb-2 sm:mb-3">Does Claude watermark its text?</h3>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  Yes. Since August 2, 2026, newer Claude models embed an imperceptible statistical watermark in generated text,
                  across the API and all Claude surfaces, worldwide, to meet the EU AI Act's transparency code. Files also receive
                  signed C2PA provenance metadata.
                </p>

                <h3 id="faq-chatgpt" className="text-lg sm:text-xl font-semibold mb-2 sm:mb-3">Does ChatGPT watermark text?</h3>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  Not as of this writing. OpenAI reportedly built a text watermarking tool around 99.9% accurate but has not
                  released it, citing concerns about evasion and unfair impact on non-native English speakers. OpenAI does attach
                  C2PA metadata to DALL·E images.
                </p>

                <h3 id="faq-remove" className="text-lg sm:text-xl font-semibold mb-2 sm:mb-3">How do you remove an AI text watermark?</h3>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  Heavy paraphrasing, translating to another language, or mixing the text substantially with your own writing all
                  degrade the statistical signal below detectability. Copy-paste and light edits do not. Note that "removability"
                  is precisely why watermarks can't be relied on as proof that content is human-written.
                </p>

                <h3 id="faq-turnitin" className="text-lg sm:text-xl font-semibold mb-2 sm:mb-3">Can Turnitin see Claude or SynthID watermarks?</h3>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  No. Turnitin and GPTZero don't have the labs' detection keys; they use their own statistical classifiers, which
                  are a separate and noisier signal — prone to false positives and beaten by paraphrasing.
                </p>

                <h3 id="faq-code" className="text-lg sm:text-xl font-semibold mb-2 sm:mb-3">Is Claude Code output watermarked?</h3>
                <p className="text-muted-foreground leading-relaxed mb-4 text-sm sm:text-base">
                  Anthropic lists Claude Code among the covered surfaces. Text output is in scope for the watermark; where Claude
                  generates supported file types, those carry C2PA metadata. Anthropic's technical documentation is the source of
                  truth for exactly which outputs are marked as it rolls out.
                </p>
              </section>

              <section className="mb-6 sm:mb-8">
                <h2 id="sources" className="text-xl sm:text-2xl font-bold mb-3 sm:mb-4">10. Sources</h2>
                <ul className="space-y-2 text-sm sm:text-base text-muted-foreground">
                  <li>• <a href="https://support.claude.com/en/articles/16266773-how-claude-marks-ai-generated-content" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Anthropic — How Claude marks AI-generated content (official)</a></li>
                  <li>• <a href="https://techcrunch.com/2026/08/11/anthropic-says-it-will-watermark-text-generated-by-its-ai-models/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">TechCrunch — Anthropic says it will watermark text generated by its AI models</a></li>
                  <li>• <a href="https://www.nature.com/articles/s41586-024-08025-4" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Nature (2024) — Scalable watermarking for identifying LLM outputs (SynthID-Text)</a></li>
                  <li>• <a href="https://deepmind.google/models/synthid/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Google DeepMind — SynthID (text, image, audio, video)</a></li>
                  <li>• <a href="https://arxiv.org/abs/2301.10226" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Kirchenbauer et al. (2023) — A Watermark for Large Language Models</a></li>
                  <li>• <a href="https://arxiv.org/abs/2303.11156" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Sadasivan et al. (2023) — Can AI-Generated Text Be Reliably Detected?</a></li>
                  <li>• <a href="https://c2pa.org/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">C2PA — Coalition for Content Provenance and Authenticity</a></li>
                </ul>
                <p className="text-muted-foreground leading-relaxed mt-4 text-xs sm:text-sm italic">
                  Watermarking policies and rollouts are moving fast under the EU AI Act. Facts here were cross-checked across
                  Anthropic's own documentation and multiple independent outlets, but check each lab's current technical docs before
                  relying on specifics.
                </p>
              </section>
            </article>
          </div>
        </div>
      </main>

      <RelatedPosts current="/blog/does-claude-watermark-text" />
      <Footer />
    </div>
  );
};

export default ClaudeWatermarkPost;
