// GSC intent ingest — turns a Google Search Console "Performance on Search"
// export into a structured demand signal the content routines read when picking
// topics. Closes the intent loop: real Search Console demand, not guesses.
//
// WEEKLY STEP (run locally, then commit the generated data/gsc-intent.md):
//   1. In GSC → Performance → Export (last 28 days) → download the ZIP.
//   2. node scripts/gsc-ingest.mjs ~/Downloads/<the-export>.zip
//   3. git add data/gsc-intent.md && git commit -m "Update GSC intent" && git push
// The daily and weekly routines read data/gsc-intent.md automatically.
//
// Accepts: a .zip export, a directory of the CSVs, or a Queries.csv path.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { execFileSync } from 'child_process'
import { join } from 'path'
import { tmpdir } from 'os'

const arg = process.argv[2]
if (!arg) {
  console.error('Usage: node scripts/gsc-ingest.mjs <gsc-export.zip | dir | Queries.csv>')
  process.exit(1)
}

// Resolve to a directory containing the GSC CSVs.
function resolveDir(p) {
  if (p.endsWith('.zip')) {
    const out = join(tmpdir(), `gsc-${Date.now()}`)
    mkdirSync(out, { recursive: true })
    execFileSync('unzip', ['-o', p, '-d', out], { stdio: 'ignore' }) // arg array — no shell
    return out
  }
  if (p.endsWith('.csv')) return p.replace(/\/[^/]+$/, '') || '.'
  return p
}

// Minimal CSV parser: handles quoted fields containing commas.
function parseCsv(text) {
  const rows = []
  let row = [], field = '', inQ = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQ) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++ }
      else if (c === '"') inQ = false
      else field += c
    } else if (c === '"') inQ = true
    else if (c === ',') { row.push(field); field = '' }
    else if (c === '\n' || c === '\r') {
      if (field !== '' || row.length) { row.push(field); rows.push(row); row = []; field = '' }
      if (c === '\r' && text[i + 1] === '\n') i++
    } else field += c
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row) }
  return rows
}

const num = (s) => Number(String(s).replace(/[%,]/g, '')) || 0

function loadCsv(dir, name) {
  const path = dir.endsWith('.csv') ? dir : join(dir, name)
  if (!existsSync(path)) return []
  const rows = parseCsv(readFileSync(path, 'utf8'))
  const header = rows.shift() || []
  return rows.filter((r) => r.length >= header.length).map((r) => Object.fromEntries(header.map((h, i) => [h.trim(), r[i]])))
}

const dir = resolveDir(arg)
const qFile = arg.endsWith('.csv') ? arg : join(dir, 'Queries.csv')
const queries = loadCsv(qFile.endsWith('.csv') ? qFile : dir, 'Queries.csv')
const pages = loadCsv(dir, 'Pages.csv')

if (!queries.length) {
  console.error(`No queries found. Looked for Queries.csv near: ${dir}`)
  process.exit(1)
}

const Q = queries.map((r) => ({
  q: r['Top queries'] || r['Query'] || '',
  clicks: num(r['Clicks']),
  impr: num(r['Impressions']),
  ctr: num(r['CTR']),
  pos: num(r['Position']),
})).filter((x) => x.q)

const P = pages.map((r) => ({
  page: (r['Top pages'] || r['Page'] || '').replace('https://aiengineerinsights.com', ''),
  clicks: num(r['Clicks']),
  impr: num(r['Impressions']),
  ctr: num(r['CTR']),
  pos: num(r['Position']),
})).filter((x) => x.page)

const topByImpr = [...Q].sort((a, b) => b.impr - a.impr).slice(0, 20)
// Striking distance: we already rank (pos 4-20) with real impressions but few clicks.
const striking = Q.filter((x) => x.pos >= 4 && x.pos <= 20 && x.impr >= 15 && x.clicks <= 1)
  .sort((a, b) => b.impr - a.impr).slice(0, 20)
// Page-1 pages bleeding clicks (rank well, low CTR).
const weakPages = P.filter((x) => x.pos <= 12 && x.impr >= 20 && x.ctr < 1)
  .sort((a, b) => b.impr - a.impr).slice(0, 12)

const date = new Date().toISOString().slice(0, 10)
const fmtQ = (x) => `- \`${x.q}\` — ${x.impr} impr · ${x.clicks} clicks · pos ${x.pos.toFixed(1)}`
const fmtP = (x) => `- ${x.page} — ${x.impr} impr · ${x.clicks} clicks · CTR ${x.ctr}% · pos ${x.pos.toFixed(1)}`

const md = `# Search Console intent signal

_Auto-generated by scripts/gsc-ingest.mjs on ${date}. Real demand from Google Search Console — the content routines read this to pick topics that serve actual, revealed intent (not guesses). Regenerate weekly._

## Top queries by impressions (what people search us for)
${topByImpr.map(fmtQ).join('\n') || '- (none)'}

## Striking-distance opportunities (we rank pos 4–20 but get ~no clicks)
These already have impressions — a focused post or a strengthened section/title can win the click. Highest leverage.
${striking.map(fmtQ).join('\n') || '- (none this window)'}

## Page-1 pages bleeding clicks (rank well, low CTR — fix title/snippet)
${weakPages.map(fmtP).join('\n') || '- (none)'}

## How the content routines should use this
- **Prefer topics and angles that serve the high-impression queries above** — this overrides guesses about intent.
- For a **striking-distance** query, we already rank; a dedicated post or a sharper title/section is likely to convert it. Treat these as the top of the backlog.
- Ignore navigational queries for other brands' official resources (they never click us).
- This is demand signal, not a mandate — stay on-niche (AI engineering) and keep quality high.
`

mkdirSync('data', { recursive: true })
writeFileSync('data/gsc-intent.md', md)
console.log(`gsc-ingest: wrote data/gsc-intent.md — ${Q.length} queries, ${P.length} pages, ${striking.length} striking-distance, ${weakPages.length} weak pages`)
